name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          # Указываем путь к файлу блокировки для корректного кеширования
          cache-dependency-path: src/package-lock.json

      - name: Install dependencies
        # Переходим в папку src перед выполнением npm install
        run: npm install
        working-directory: ./src

      - name: Build
        # Переходим в папку src перед выполнением npm run build
        run: npm run build
        working-directory: ./src

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Путь до итоговой сборки относительно корня репозитория
          path: "./src/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
